// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyUrl.Api.Data;

#nullable disable

namespace TinyUrl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103115928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TinyUrl.Api.Models.TinyUrls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TinyUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
